steps:
  # SendGrid Cloud Function
  - id: "sendgrid-cloud-function-zip"
    name: "gcr.io/$PROJECT_ID/zip"
    args: ["-r", "sendgrid-cloud-function.zip", "."]
    dir: "cloud-functions/sendgrid"
    waitFor: ["-"]
  - id: "sendgrid-cloud-function-upload"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "storage",
        "cp",
        "sendgrid-cloud-function.zip",
        "gs://${_SENDGRID_CLOUD_FUNCTION_SOURCE_ARCHIVE_BUCKET}/sendgrid-cloud-function.zip",
        "--quiet",
      ]
    dir: "cloud-functions/sendgrid"
    waitFor: ["sendgrid-cloud-function-zip"]
  # Deployment
  - id: "terraform-init"
    name: "gcr.io/$PROJECT_ID/terraform"
    args:
      [
        "-chdir=deployment/terraform/environment",
        "init",
        "-backend-config=bucket=${_TFSTATE_BUCKET}",
      ]
  - id: "terraform-apply"
    name: "gcr.io/$PROJECT_ID/terraform"
    args: ["-chdir=deployment/terraform/environment", "apply", "-auto-approve"]
    env:
      - "TF_VAR_project_id=${PROJECT_ID}"
      - "TF_VAR_region=${_REGION}"
      - "TF_VAR_email_from=${_EMAIL_FROM}"
      - "TF_VAR_sendgrid_api_key_secret_id=${_SENDGRID_API_KEY_SECRET_ID}"
      - "TF_VAR_sendgrid_cloud_function_source_archive_bucket=${_SENDGRID_CLOUD_FUNCTION_SOURCE_ARCHIVE_BUCKET}"
      - "TF_VAR_sendgrid_cloud_function_source_archive_object=sendgrid-cloud-function.zip"
