steps:
  # SendGrid Cloud Function
  - id: 'sendgrid-cloud-function-upload'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        "storage",
        "cp",
        "sendgrid-cloud-function.zip",
        "gs://${_SENDGRID_CLOUD_FUNCTION_SOURCE_ARCHIVE_BUCKET}/sendgrid-cloud-function.zip",
        "--quiet",
      ]
    dir: 'cloud-functions/sendgrid'
    waitFor: ["sendgrid-cloud-function-zip"]
  # Deployment
  - id: 'terraform-init'
    name: 'gcr.io/$PROJECT_ID/terraform'
    args:
      [
        "-chdir=deployment/google-cloud/terraform/environment",
        "init",
        "-backend-config=bucket=${_TFSTATE_BUCKET}",
      ]
  - id: 'terraform-apply'
    name: 'gcr.io/$PROJECT_ID/terraform'
    entrypoint: 'bash'
    args:
      [
        "-c",
        "terraform",
        "-chdir=deployment/google-cloud/terraform/environment",
        "apply",
        "-auto-approve",
        '-var="sendgrid_api_key=${SENDGRID_API_KEY}"',
      ]
    env:
      - "TF_VAR_project_id=${PROJECT_ID}"
      - "TF_VAR_region=${_REGION}"
      - "TF_VAR_email_from=${_EMAIL_FROM}"
      - "TF_VAR_sendgrid_cloud_function_source_archive_bucket=${_SENDGRID_CLOUD_FUNCTION_SOURCE_ARCHIVE_BUCKET}"
      - "TF_VAR_sendgrid_cloud_function_source_archive_object=sendgrid-cloud-function.zip"
    secretEnv: ['SENDGRID_API_KEY']
availableSecrets:
  secretManager:
    - versionName: '${_SENDGRID_API_KEY_SECRET_VERSION}'
      env: 'SENDGRID_API_KEY'
